### ISSUE TITLE
Chastikeyinfo no longer working

### ISSUE THREAD

**Issue by ocmodder** [rileyio/chastikeyinfo#3]
Due to an update to Discord (Desktop) on 25/11/2020 the plugin is no longer able to show info next to names in Rooms/DMs. No errors showing in console.

**Comment by rileyio** [comment]
I sorta fixed in 2.0.3 tonight.  

The request for the node's react instance no longer seems to work, there's like little to no BD documentation on this, I dug through some other plugins to see how they changed (and saw at least one who very clearly changed up how they did it as the old method ppl did it was still there just never used/commented out), they seem to be using the Patcher available under the Plugin Lib, but I don't know enough about it to use it right now.

I wasn't in the mood to dig too deep tonight but wanted to fix it, so for now its just piggybacking off the user's Avatar URL which contains their Discord ID.  For now that works, but, if someone lacks an ID it does not.

There may be other issues doing it this way, but for now it seems to work (emphasis on the "seems", lol)  Perhaps someone better with react could look into it ;)   I hardly use CK these days, so my time investment in this plugin is taking a nosedive and I don't particularly feel like a rewrite at this point in time.

**Comment by rileyio** [comment]
I sorta fixed in 2.0.3 tonight.

The request for the node's react instance no longer seems to work (this is where I was getting the message Author ID from), there's like little to no BD documentation on this, I dug through some other plugins to see how they changed (and saw at least one who very clearly changed up how they did it as the old method ppl did it was still there just never used/commented out), they seem to be using the Patcher available under the Plugin Lib, but I don't know enough about it to use it right now.

**Comment by rileyio** [comment]
Fixed in `2.1.0`.
